### ISSUE TITLE
Decide the size/scope of initial dataset

### ISSUE THREAD

**Issue by Jumperkables** [Visual-modelling/Visual-modelling#6]

**Comment by zhemingzuo** [comment]
My suggestions for our initial dataset collection:

- Resolution of each frame: 64-by-64 pixels (a common setting in the realm of video prediction, e.g. [Moving MNIST](http://www.cs.toronto.edu/~nitish/unsupervised_video/)

- Add "moving pepper noise" or "moving noisy object" (flying across both foreground and background) as shown in Moving MNIST

- Collect a 2-D corpus and a 3-D set

- Number of classes and number of videos per class may be determined by our next catchup (we need to think about the number of physical properties, illumination changes, objects, shape of noisy object(s), etc. in our dataset), typical datasets in the domain: Moving [MNIST](http://www.cs.toronto.edu/~nitish/unsupervised_video/), KTH action, [Weizmann action](http://www.wisdom.weizmann.ac.il/~vision/SpaceTimeActions.html), [MSR Actions](https://www.microsoft.com/en-us/download/details.aspx?id=52315), [Robotic Pushing dataset](https://sites.google.com/site/brainrobotdata/home/push-dataset), [NORB dataset](https://cs.nyu.edu/~yann/research/norb/), [UCF-50](https://www.crcv.ucf.edu/data/UCF50.php), [UCF-101](https://www.crcv.ucf.edu/data/UCF101.php)
